language: rust
rust:
  - nightly
sudo: false
cache: cargo

before_script:
- rustup component add rustfmt

jobs:
    include:
        - language: go
          script:
          - bash ./.travis.build.sh
