language: rust
rust:
  - nightly
sudo: false
cache: cargo

before_script:
- rustup component add rustfmt
script:
- bash ./.travis.build.sh

jobs:
    include:
        - language: go
          go: 1.12.x
          script:
          - bash ./.travis.build.sh
