language: rust
rust:
  - nightly
sudo: false
cache: cargo

before_script:
- rustup component add rustfmt

matrix:
    include:
        - language: rust
          rust: nightly
          script:
          - bash ./.travis.build.sh 0

        - language: go
          go: 1.12.x
          script:
          - bash ./.travis.build.sh 1
